exam/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
# from django.contrib.auth.views import logout


app_name='exam'

urlpatterns = [
	path('', views.index , name='index'),
	path('logout/', views.logout_user ,name='logout-user'),
	path('register/', views.register ,name='register'),
	path('login/', views.login_user ,name='login-user'),
	path('user/profile/', views.user_profile ,name='user-profile'),
    path('applicant/assignment/start/',views.applicant_exam ,name='applicant-exam'),
    path('applicant/assignment/result/',views.result ,name='applicant-result'),
    path('organisation/admin/assignment/',views.admin_assignment ,name='admin-assignment'),
    path('organisation/admin/assignment/create',views.admin_assignment_create ,name='admin-assignment-create'),
    path('organisation/admin/assignment/update/<int:id>/',views.admin_assignment_update ,name='admin-assignment-update'),
    path('organisation/admin/assignment/delete/',views.admin_assignment_delete ,name='admin-assignment-delete'),
    path('organisation/admin/exam/',views.admin_exam ,name='admin-exam'),
    path('organisation/admin/exam/create/',views.admin_exam_create ,name='admin-exam-create'),
    path('organisation/admin/exam/update/<int:id>/',views.admin_exam_update ,name='admin-exam-update'),
    path('organisation/admin/exam/delete/',views.admin_exam_delete ,name='admin-exam-delete'),
    path('organisation/admin/applicants/',views.admin_applicants_list ,name='admin-applicants'),
    path('organisation/admin/applicant/create/',views.admin_applicant_create ,name='admin-applicant-create'),
    path('organisation/admin/applicant/update',views.admin_applicant_update ,name='admin-applicant-update'),
    path('organisation/admin/applicant/delete/',views.admin_applicant_delete ,name='admin-applicant-delete'),
    path('organisation/admin/questions/',views.admin_questions ,name='admin-questions'),
    path('organisation/admin/question/create/',views.admin_question_create ,name='admin-question-create'),
    path('organisation/admin/question/update/<int:id>/',views.admin_question_update ,name='admin-question-update'),
    path('organisation/admin/question/delete/',views.admin_question_delete ,name='admin-question-delete'),
    path('organisation/admin/assignment/result/<int:id>/',views.admin_assignment_result ,name='admin-assignment-result'),
    path('organisation/admin/applicants/filter/',views.admin_applicants_filter ,name='admin-applicants-filter'),
    path('organisation/admin/questions/filter/',views.admin_questions_filter ,name='admin-questions-filter'),
    path('organisation/admin/exams/filter/',views.admin_exams_filter ,name='admin-exams-filter'),
    path('organisation/admin/assignments/filter/',views.admin_assignments_filter ,name='admin-assignments-filter'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myexamsite/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
	path('admin/', admin.site.urls),
    path('', include('exam.urls',namespace='exam')),

]

exam/models.py
from django.db import models
from users.models import User
from django.template.defaultfilters import slugify
from django.core.validators import FileExtensionValidator
from django.conf import settings

# Create your models here.

class Attachment(models.Model):
    ''' attachment for question '''
    name = models.CharField(max_length=50)
    attachment = models.FileField(upload_to = 'question/pictures',validators=[FileExtensionValidator(allowed_extensions=['pdf','jpg','jpeg','gif','tiff','exiff','odt','png','doc','docx','txt'])])
    description = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    ''' Tags for question '''
    name = models.CharField(max_length=50,unique=True)
    name_slug =  models.CharField(max_length=50,blank=True,null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name) # set the slug explicitly
        super(Tag, self).save(*args, **kwargs) # call Django's save()

class Question(models.Model):
    ''' create question for exam '''
    question_choice = (
        ('choice','Choice'),
        ('text','Text'),
        ('program','Program'),
        )
    question_type = models.CharField(max_length=10,choices=question_choice,default='choice')
    name_slug = models.CharField(max_length=50,blank=True,null=True)
    question_text = models.TextField(blank=False ,unique = True)
    hint = models.CharField(max_length=50,blank=True,null=True)
    pub_date = models.DateTimeField('date published',blank=True,null=True)
    attachments = models.ManyToManyField(Attachment,blank=True)
    tags = models.ManyToManyField(Tag,blank=True)
    answer = models.ForeignKey('exam.Choice',on_delete=models.CASCADE,related_name='answer',blank=True,null=True)

    def __str__(self):
        return self.question_text

    # def save(self, *args, **kwargs):
    #     self.name_slug = slugify(self.name) # set the slug explicitly
    #     super(Question, self).save(*args, **kwargs) # call Django's save()

class Choice(models.Model):
    ''' Choices for question,if question type is choice

    '''
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    name_slug = models.CharField(max_length=50)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.choice_text) # set the slug explicitly
        super(Choice, self).save(*args, **kwargs) # call Django's save()

class Answer(models.Model):
    ''' Answer for question, if question type is text.'''
    question = models.ForeignKey('exam.Question',on_delete=models.CASCADE,related_name='answertext')
    answer = models.TextField(default=None)
    name_slug = models.CharField(max_length=50,blank=True,null=True)

    def __str__(self):
        return str(self.question)

class Exam(models.Model):
    '''create exam for applicant assignment'''
    name = models.CharField(max_length=100,blank = False,unique=True)
    name_slug = models.CharField(max_length=100)
    question_paper = models.ManyToManyField(Question)
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name) # set the slug explicitly
        super(Exam, self).save(*args, **kwargs) # call Django's save()

class AnswerSheet(models.Model):
    '''Answer sheet  to store the applicant answers'''
    assignment=models.ForeignKey('exam.Assignment',on_delete=models.CASCADE,blank=True,null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    answer = models.ForeignKey(Choice,on_delete=models.CASCADE,blank=True,null=True)
    exam = models.ForeignKey(Exam,on_delete=models.CASCADE)
    answer_text = models.TextField(blank=True,null=True)

    def __str__(self):
        return str(self.user)+"------"+str(self.exam)+"----"+str(self.question)

class Attempt(models.Model):
    '''Applicant attempts to write the exam'''

    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True,null=True)
    duration = models.FloatField(blank=True,null=True,help_text='Duration in seconds')

    def __str__(self):

        return str(self.start_time)
class Assignment(models.Model):
    """ create assignment for applicant"""
    PENDING = 'pending'
    ABORTED = 'aborted'
    FINISHED = 'finished'
    TIMEOUT = 'timeout'

    PASS = 'pass'
    FAIL = 'fail'
    STATUS_CHOICE = (
        (PENDING,'Pending'),
        (ABORTED,'Aborted'),
        (FINISHED,'Finished'),
        (TIMEOUT,'Timeout'),
        )
    EXAM_CHOICE= (
        (PASS,'Pass'),
        (FAIL,'Fail'),
        )

    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam,on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    status = models.CharField(max_length=10,choices=STATUS_CHOICE,default=PENDING)
    exam_status = models.CharField(max_length=10,choices=EXAM_CHOICE,default=None,blank=True,null=True)
    name_slug = models.CharField(max_length=50,blank=True,null=True)
    attempts = models.ManyToManyField(Attempt,blank=True)
    duration = models.FloatField(help_text='Duration in seconds')


    def __str__(self):
        return str(self.user)+" "+str(self.exam)

users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.base_user import BaseUserManager
from datetime import datetime
from django.core.validators import RegexValidator




class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)
class User(AbstractBaseUser,PermissionsMixin):
	gender_choices = (
        ('male','Male'),
        ('female','Female'),
        ('others','Others'),
        )
	email = models.EmailField(verbose_name='email address',max_length=255,unique=True,)
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	gender = models.CharField(max_length=5,choices=gender_choices,default='male')
	phone_regex = RegexValidator(regex=r'^(0|91)?[789][0-9]{9}$', message="Enter valid phone number")
	mobile = models.CharField(max_length=13,validators=[phone_regex])
	date_of_birth = models.DateField(blank=True,null=True)
	date_joined = models.DateTimeField('date joined',default=datetime.now)
	is_active=models.BooleanField(default=True)
	is_staff=models.BooleanField(default=False)
	is_admin=models.BooleanField(default=False)
	username=models.CharField(max_length=255,blank=True,null=True)
	objects=UserManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	def __str__(self):
		return self.first_name+" "+self.last_name

exam/templates/exam/admin_applicants.html
{% extends 'exam/admin-base.html' %}

{% block content %}

<div class="col-lg-12 filters-row no-padding-on-mobile">
<h4>Applicants <span class="glyphicon glyphicon-filter"></span></h4>
<form id="filter_form"class="form-inline" method="post" accept-charset="utf-8">
<div class="col-lg-2 form-group no-padding-on-mobile">
<label class="float-right" for="id_email">Email</label>
<input class="form-control" type="text" id="id_email" name="email" value="">
</div>
<div class="col-lg-2 form-group no-padding-on-mobile">
<label class="float-right" for="id_first_name">First Name</label>
<input class="form-control" type="text" id="id_first_name" name="first-name" value="">
</div>
<div class="col-lg-2 form-group no-padding-on-mobile" >
<label class="float-right" for="id_last_name">Last Name</label>
<input class="form-control" type="text" id="id_last_name" name="last-name" value="">
</div>
<div class="col-lg-2 form-group no-padding-on-mobile">
<label class="float-right" for="id_group">Group</label>
<select class="form-control selectpicker" data-live-search="true" id="id_group" name="group">
<option value="" selected>---</option>
<option value="None">None</option>
{% for group in groups %}
<option value="{{ group.id }}">{{ group }}</option>
{% endfor %}
</select>
</div>
<div class=" col-lg-2 form-group no-padding-on-mobile">
<label class="float-right" for="id_active">Is Active</label>
<select class="form-control selectpicker" id="id_active" name="active">
<option value="" selected>---</option>
<option value="True">Yes</option>
<option value="False">No</option>
</select>
<span >
<button id="id_search" class="btn btn-warning form-control applicants-search" type="submit">
	<span class="glyphicon glyphicon-search"></span>
</button>
</span>
</div>
</form>
</div>

<div class="container" id="ajaxbody">
<form action="" method="POST" accept-charset="utf-8">
{% csrf_token %}
<a style="float:right;" href="{% url 'exam:admin-applicant-create' %}">Add Applicant</a></br>
{% if applicant_list %}
<table class="table">
<thead>

	<tr>
		<th>
			Email
		</th>
		<th>
			First Name
		</th>
		<th>
			Last Name
		</th>
		<th>
			Group
		</th>
		<th>
			Is Active
		</th>
		<th>
			Action
		</th>
	</tr>
</thead>
<tbody id="tbodyid">
	{% for applicant in applicant_list %}
	<tr>
		<td><span class="td_email"><a href="{% url "exam:admin-applicant-update" %}?email={{ applicant.email }}">{{ applicant.email }}</a><span></td>
		<td><span class="td_first_name">{{ applicant.first_name|default_if_none:"---" }}<span></td>
		<td><span class="td_last_name">{{ applicant.last_name |default_if_none:"---" }}</span></td>
		<td><span class="td_group">{{ applicant.groups.all.first|default_if_none:None }}</td>
		<td><span class="td_active">{% if applicant.is_active is True %} Yes {% else %} No {% endif %}</span></td>
		<td><button class="btn btn-link delete-button" type="submit" data-applicant-id="{{ applicant.id }}" ><span class="glyphicon glyphicon-trash"></span></button></td>

	</tr>
	{% endfor %}
	</tbody>
</table>
{% else %}
<h2 id="menu_heading">No applicants are available</h2>
{% endif %}

<script type="text/javascript">
$(document).ready(function() {

	function titleCase(str) {
  		return str.toLowerCase().split(' ').map(function(word) {
    	return word.replace(word[0], word[0].toUpperCase());
  		}).join(' ');
	}

    $('.delete-button').click(function(e) {
        e.preventDefault()
        var r = confirm('Are you sure want to delete ?.');
        var data_applicant_id = $(this).attr('data-applicant-id');
        var csrf_token = $('input[name="csrfmiddlewaretoken"]').val()
        if (r == true) {
        	$('.loading').show();
            $.post('{% url "exam:admin-applicant-delete" %}', {
                'data_applicant_id': data_applicant_id,
                'csrfmiddlewaretoken': csrf_token,
            }, function(data) {
				window.location='.'


            });

        } else {

            return false;
        }

    });

    $('.applicants-search').click(function(event){
    	event.preventDefault()
        	$.ajax({
            url: '{% url "exam:admin-applicants-filter" %}',
            data: $('#filter_form').serialize(),
            method: "POST",
            success: function(data) {
           		var $tr = $(".table").find('tr:last').clone(true)
                $("#tbodyid").empty()
            	var data_array=data['applicants']
            	for(item in data_array){
	          		var email = data_array[item]['email']
	          		var first_name = data_array[item]['first_name']
	          		var last_name = data_array[item]['last_name']
	          		var group = data_array[item]['groups__name']
	          		var active = data_array[item]['is_active']
	          		if(active==true){
	          			active='Yes'
	          		}
	          		else{
	          			active='No'
	          		}
	          		if (!group){
	          			group="None"
	          		}
	          		$("#tbodyid").append($tr)
	          		$(".table").find('tr:last .td_email').text(email)
	          		$(".table").find('tr:last .td_first_name').text(first_name)
	          		$(".table").find('tr:last .td_last_name').text(last_name)
	          		$(".table").find('tr:last .td_group').text(group)
	          		$(".table").find('tr:last .td_active').text(active)
	          		var $tr = $(".table").find('tr:last').clone(true)
          		}

            }
        })

    });

});
</script>
</div>

{% endblock %}

exam/templates/exam/admin_assignment.html
{% extends 'exam/admin-base.html' %}

{% block content %}

<div class="col-lg-12 filters-row no-padding-on-mobile">
<h4>Assignments <span class="glyphicon glyphicon-filter"></span></h4>
<form id="filter_form"class="form-inline" method="post" accept-charset="utf-8">
<div class="no-padding-left col-lg-2 form-group no-padding-on-mobile" style="padding-right: 15px;">
<label class="float-right" for="id_applicant">Applicant</label>
<input class="form-control" type="text" id="id_applicant" name="applicant" value="">
</div>
<div class="no-padding-left col-lg-2 form-group no-padding-on-mobile" style="padding-right:10px;">
<label class="float-right" for="id_exam_name">Exam Name</label>
<input class="form-control" type="text" id="id_exam_name" name="exam-name" value="">
</div>
<div class="no-padding-left col-lg-2 form-group no-padding-on-mobile">
<label class="float-right" for="id_status">Status</label>
<select class="form-control selectpicker" id="id_status" name="status">
<option value="" selected>---</option>
{% for state in status %}
<option value="{{ state.0 }}">{{ state.1 }}</option>

{% endfor %}
</select>
</div>
<div class="no-padding-left col-lg-2 form-group no-padding-on-mobile">
<label class="float-right" for="id_score">Score</label>
<input class="form-control" type="text" id="id_score" name="score" value="">
</div>
<div class="no-padding-left col-lg-2 form-group no-padding-on-mobile">
<label class="float-right" for="id_result">Result</label>
<select class="form-control selectpicker" id="id_result" name="exam-result">
<option value="" selected>---</option>
{% for state in exam_status %}
<option value="{{ state.0 }}">{{ state.1 }}</option>

{% endfor %}
</select>
<span >
<button id="id_search" class="btn btn-warning form-control assignments-search" type="submit">
	<span class="glyphicon glyphicon-search"></span>
</button>
</span>
</div>
</form>
</div>

<div class="container" id="ajaxbody">

<form action="" method="POST" accept-charset="utf-8">
{% csrf_token %}
<a style="float:right;" href="{% url 'exam:admin-assignment-create' %}">Add Assignment</a>
</form>
</br>
{% if assignment_list %}
<table class="table">
	<thead>
	<tr>
		<th>
			Applicant
		</th>
		<th>
			Exam Name
		</th>
		<th>
			Status
		</th>
		<th>
			Score
		</th>
		<th>
			Result
		</th>
		<th>
			Action
		</th>

	</tr>
</thead>
<tbody id="tbodyid">
	{% for assignment in assignment_list %}
	<tr>
		<td><span class="td_applicant"><a href="{% url 'exam:admin-assignment-update' id=assignment.id %}">{{ assignment.user }}</a></span></td>
		<td><span class="td_exam_name">{{ assignment.exam }}</span></td>
		<td><span class="td_status">{{ assignment.get_status_display }}</span></td>
		<td><span class="td_score">{{ assignment.score }}</span></td>
		<td><span class="td_result">{{ assignment.get_exam_status_display|default_if_none:"---" }}</span></td>
		<td><button class="btn btn-link delete-button" type="submit" data-assignment-id="{{ assignment.id }}" ><span class="glyphicon glyphicon-trash"></span></button></td>

	</tr>
	{% endfor %}
</tbody>
</table>
{% else %}
<h2 id="menu_heading">No Assignments are available</h2>
{% endif %}

<script type="text/javascript">
$(document).ready(function() {

	function titleCase(str) {
  		return str.toLowerCase().split(' ').map(function(word) {
    	return word.replace(word[0], word[0].toUpperCase());
  		}).join(' ');
	}

    $('.delete-button').click(function(e) {
        e.preventDefault()
        var r = confirm('Are you sure want to delete ?.');
        var data_assignment_id = $(this).attr('data-assignment-id');
        var csrf_token = $('input[name="csrfmiddlewaretoken"]').val()
        if (r == true) {
        	$('.loading').show();
            $.post('{% url "exam:admin-assignment-delete" %}', {
                'data_assignment_id': data_assignment_id,
                'csrfmiddlewaretoken': csrf_token,
            }, function(data) {
				window.location='.'

            });
        } else {
           return false;
        }

    });

    $('.assignments-search').click(function(event){
    	event.preventDefault()
        	$.ajax({
            url: '{% url "exam:admin-assignments-filter" %}',
            data: $('#filter_form').serialize(),
            method: "POST",
            success: function(data) {
           		var $tr = $(".table").find('tr:last').clone(true)
                $("#tbodyid").empty()
            	var data_array=data['assignments']
            	console.log(data_array)
            	for(item in data_array){
	          		var first_name = data_array[item]['user__first_name']
	          		var last_name = data_array[item]['user__last_name']
	          		var applicant =first_name.concat("  ",last_name)
	          		var exam_name = data_array[item]['exam__name']
	          		var status = titleCase(data_array[item]['status'])
	          		var score = data_array[item]['score']
	          		var result = data_array[item]['exam_status']
	          		if (result){
	          			result=titleCase(result)
	          		}
	          		else{
	          			result='---'
	          		}
	          		$("#tbodyid").append($tr)
	          		$(".table").find('tr:last .td_applicant').text(applicant)
	          		$(".table").find('tr:last .td_exam_name').text(exam_name)
	          		$(".table").find('tr:last .td_status').text(status)
	          		$(".table").find('tr:last .td_score').text(score)
	          		$(".table").find('tr:last .td_result').text(result)
	          		var $tr = $(".table").find('tr:last').clone(true)
          		}

            }
        })

    });

});
</script>
</div>

{% endblock %}

exam/templates/exam/admin_assignment_result.html
{% extends 'exam/admin-base.html' %}

{% block content %}
<div class="row heading">
    <div class="col-lg-12">
    <h4 align="center">Applicant Name - <span><a href="{% url 'exam:admin-applicant-update' %}?user={{ assignment.user.username }}">{{ assignment.user.get_full_name }}</a></span>&nbsp;&nbsp;&nbsp;&nbsp;
    Exam Name - <span><a href="{% url 'exam:admin-exam-update' id=assignment.exam.id %}">{{ assignment.exam.name }}</a></span>&nbsp;&nbsp;&nbsp;&nbsp;
    Assignment Status - <span>{{ assignment.get_status_display }}</span>&nbsp;&nbsp;&nbsp;&nbsp;
    Exam Status - <span>{{ assignment.get_exam_status_display|default_if_none:"---" }}</span> </h4>
    </div>
</div>
{% if answer_sheet %}
<ol>
    <form action="" method="post">
        {% csrf_token %}
        {% for data in answer_sheet %}
        <h3><li><a href="{%url 'exam:admin-question-update' id=data.question.id %}">{{ data.question.question_text }}</a></li></h3>
        {% if data.question.get_question_type_display == 'Choice' %}
        <h4>Applicant Answer is: <span>{{ data.answer|default_if_none:"---" }}</span></h4>
        <h4>Correct Answer is: <span>{{ data.question.answer|default_if_none:"---" }}</span></h4>
        {% else %}
        <h4>Applicant Answer is: <span>{{ data.answer_text|default_if_none:"---" }}</span></h4>
        <h4>Correct Answer is: <span>{{ data.question.answertext.first.answer|default_if_none:"---" }}</span></h4>
        {% endif %}
        {% endfor %}
    </form>
</ol>
{% else %}
<h3 id="menu_heading">Answer sheet not available.</h3>
{% endif %}

{% endblock %}

exam/templates/exam/admin_exam.html
{% extends 'exam/admin-base.html' %}


{% block content %}

<div class="col-lg-12 filters-row no-padding-on-mobile">
<h4>Exams <span class="glyphicon glyphicon-filter"></span></h4>
<form id="filter_form"class="form-inline" method="post" accept-charset="utf-8">
<div class="no-padding-left col-lg-3 form-group no-padding-on-mobile" style="padding-right: 15px;">
<label class="float-right" for="id_exam_name">Exam Name</label>
<input class="form-control" type="text" id="id_exam_name" name="exam-name" value="">
</div>
<div class="no-padding-left col-lg-3 form-group no-padding-on-mobile" style="padding-right:10px;">
<label class="float-right" for="id_question_description">Question</label>
<input class="form-control" type="text" id="id_question_description" name="question-description" value="">
<span>
<button id="id_search" class="btn btn-warning form-control exams-search" type="submit">
	<span class="glyphicon glyphicon-search"></span>
</button>
</span>
</div>
</form>
</div>


<div class="container" id="ajaxbody">

<form action="" method="POST" accept-charset="utf-8">
{% csrf_token %}
<a style="float:right;" href="{% url 'exam:admin-exam-create' %}">Add Exam</a></br>
{% if exam_list %}
<table class="table">
<thead>
	<tr>
		<th>
			Exam Name
		</th>
		<th>
			Questions
		</th>
		<th>
			Action
		</th>

	</tr>
</thead>
<tbody id="tbodyid">
	{% for exam in exam_list %}
	<tr>
		<td><span class="td_exam_name"><a name="exam.id" href="{% url 'exam:admin-exam-update' id=exam.id %}">{{ exam.name }}</a></span></td>
		<td><span class="td_question_description">{% for question in exam.question_paper.all %}
			{% for tag in question.tags.all %}
			{{ tag }}&nbsp;,
			{% endfor %}
			{% endfor %}
		</span></td>
		<td><button class="btn btn-link delete-button" type="submit" data-exam-id="{{ exam.id }}" ><span class="glyphicon glyphicon-trash"></span></button></td>

	</tr>
	{% endfor %}
</tbody>
</table>
{% else %}
<h3 id="menu_heading">No Exam are availabale</h3>
{% endif %}

<script type="text/javascript">
$(document).ready(function() {

    $('.delete-button').click(function(e) {
        e.preventDefault()
        var r = confirm('Are you sure want to delete ?.');
        var data_exam_id = $(this).attr('data-exam-id');
        var csrf_token = $('input[name="csrfmiddlewaretoken"]').val()
        if (r == true) {
            $('.loading').show();
            $.post('{% url "exam:admin-exam-delete" %}', {
                'data_exam_id': data_exam_id,
                'csrfmiddlewaretoken': csrf_token,
            }, function(data) {
				window.location='.'

            });

        } else {

            return false;
        }

    });

    $('.exams-search').click(function(event){
    	event.preventDefault()
        	$.ajax({
            url: '{% url "exam:admin-exams-filter" %}',
            data: $('#filter_form').serialize(),
            method: "POST",
            success: function(data) {
           		var $tr = $(".table").find('tr:last').clone(true)
                $("#tbodyid").empty()
            	var data_array=data['exams']
            	console.log(data_array)
            	for(item in data_array){
	          		var exam_name = data_array[item]['name']
	          		var question_tags= data_array[item]['question_paper']
	          		$("#tbodyid").append($tr)
	          		$(".table").find('tr:last .td_question_type').text(exam_name)
	          		$(".table").find('tr:last .td_question_description').text(question_tags)
	          		var $tr = $(".table").find('tr:last').clone(true)
          		}

            }
        })

    });

});
</script>
</div>

{% endblock %}

exam/templates/exam/admin_home.html
{% extends 'exam/admin-base.html' %}
{% block title %} {{ block.super }} || Home {% endblock %}

{% block content %}


{% endblock %}

exam/templates/exam/invalid_access.html
{% extends 'exam/applicant-base.html' %}

{% block title %} {{ block.super }} || Home {% endblock %}

 {% block content %}

 <h3 id="menu_heading">Access Denied</h3>

{% endblock %}

exam/templates/exam/login.html
{% extends 'exam/base.html' %}

{% block title %}{{ block.super }} || login Page{% endblock %}

{% block content %}
<h2 id="menu_heading">Login</h2>
{% if failure %}
	<h4 id="heading_info">Invalid Credentials</h4>
{% endif %}
	<form method="POST" action=".">
	{% csrf_token %}
		{{ login_form.as_p }}
		<button class="btn btn-success" type="submit">Login</button>
		<button class="btn btn-default" type="reset">reset</button>
	</form>
	<h4>New User ?. <a href="{% url 'exam:register' %}">Register</a></h4>

{% endblock %}